version: '3.7'
services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: 'Test'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'pass'
      MYSQL_ROOT_PASSWORD: 'pass'
    ports:
      - '3306:3306'
    volumes:
      - mysql-db:/var/lib/mysql
      - ./init-db.sql:/docker-entrypoint-initdb.d/1.sql

volumes:
  mysql-db: